### test connection

GET http://localhost:3000/ HTTP/1.1

### signup

POST http://localhost:3000/signup HTTP/1.1
Content-Type: application/x-www-form-urlencoded

first_name=test
&last_name=last_test
&password=123
&password_verify=123
&email=test@gmail.com

### signup another user

POST http://localhost:3000/signup HTTP/1.1
Content-Type: application/x-www-form-urlencoded

first_name=another
&last_name=last_another
&password=1234
&password_verify=1234
&email=another@gmail.com

### signup another user incorrect password

POST http://localhost:3000/signup HTTP/1.1
Content-Type: application/x-www-form-urlencoded

first_name=another2
&last_name=another2_last
&password=123
&password_verify=1234
&email=another@gmail.com

### signup incomplete post body

POST http://localhost:3000/signup HTTP/1.1
Content-Type: application/x-www-form-urlencoded

first_name=another3
&last_name=another3_last
&password=123
&email=another@gmail.com


### login

POST http://localhost:3000/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

email=test@gmail.com
&password=123

### login incorrect password

POST http://localhost:3000/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

email=test@gmail.com
&password=1234


### login another user

POST http://localhost:3000/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

email=another@gmail.com
&password=1234




### template

GET http://localhost:3000/api/v1/ HTTP/1.1



### change Authorization header to token that returns from login

GET http://localhost:3000/api/v1/ HTTP/1.1
Authorization: Bearer 
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFub3RoZXJAZ21haWwuY29tIiwiaWF0IjoxNjE2ODc3Mjc4LCJleHAiOjE2MTY4NzkwNzh9.2Odzqy16jaVBTT-Wx5AdORbbS20kE8Zle4sVGHbhd3U