

# set correct authorization header after login.
@host = http://localhost:3000
@contentType = application/x-www-form-urlencoded
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDMsImZpcnN0X25hbWUiOiJOZXcgTmFtZSAzIiwibGFzdF9uYW1lIjoiMTIzIiwiZW1haWwiOiJ0ZXN0MkBnbWFpbC5jb20iLCJpYXQiOjE2MTY5NTQzODksImV4cCI6MTYxNjk1NjE4OX0.EeaoFa3TeCIfp70X15TSWp7pcpxWJZF8VxRuocfuc30


### test connection

GET  {{host}}/ 

### signup

POST {{host}}/signup
Content-Type: {{contentType}}

first_name=test
&last_name=la_test
&password=123
&password_verify=123
&email=test3@gmail.com

### login 

POST {{host}}/login
Content-Type: {{contentType}}

email=another@gmail.com
&password=1234

###

POST {{host}}/api/v1/posts 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDYsImZpcnN0X25hbWUiOiJhbm90aGVyMiIsImxhc3RfbmFtZSI6ImFub3RoZXIyX2xhc3QiLCJlbWFpbCI6ImFub3RoZTJyQGdtYWlsLmNvbSIsImlhdCI6MTYxNjk1MTkzMCwiZXhwIjoxNjE2OTUzNzMwfQ.i0f8rI-_Oa3R1h-8Zt-fZfYLXENv7ESwT0NXGQ7dYUQ
Content-Type: application/x-www-form-urlencoded

content=Hello This is another Post.


### Test 

GET {{host}}/api/v1/
Authorization: Basic {{authToken}}
### returns information about logged in user

GET {{host}}/api/v1/users/me
Authorization: Bearer {{authToken}}


### edit profile info of logged in user

POST {{host}}/api/v1/users/me
Authorization: Bearer {{authToken}}
Content-Type: {{contentType}}

first_name=Hadi
&last_name=Ahmadi
&bio=this is my bio
&gender=Male
&email=ahmadihadi374@gmail.com
&year_of_birth=2002
&phone=0787771034

#file
&profile_image= 
&cover_image=